### PR TITLE
Add expo plugin

### PR DESCRIPTION
**Pull request by NoZiL**
Hey guys, great lib that I am using on a new project 👏 .
Since I am using expo on it, I'm sharing the plugin implementation. Hope it will be useful to others or merged in this repo 👍

### CODE REVIEW

**Comment by hirbod** [comment]
@NoZiL I've been asking the support a couple of weeks for that plugin, so thanks a TON for taking care here. My time was too limited working on this. I had a chat with an Expo core team member, they told me, that enabling multiDex + extending the class is most likely not needed.

Quote:
```
> multidex
as far a i can tell, the `MultiDexApplication` acts like a support library for old android. 
after android 5, the ART java vm natively support multiple dex files.
so yes, i think you don't have to patch java file in this case.
```

I would love to see some clarification here, maybe someone from imgly wants to give an answer here.
@NoZiL, could you release this plugin as a standalone library, maybe updating to the latest versions? 
Since your PR is unanswered since 26th of October.

**Comment by hirbod** [comment]
For now, here is a local config-plugin I've created based on the work from @NoZiL which works fine for me.
Since the plugin has to be configureable, it's actually better to use a local, editable one, instead this PR (only useful when configs are editable)

1. edited my app.config.js (or .json) and added following to the plugin section
```js
  plugins: [
    ['./plugins/withReactNativeVideoEditorSDK']
  ],
```
2. created a folder `plugins` in my project root
3. created withReactNativeVideoEditorSDK.js inside of folder `plugins`
4. inserted following code

```js
const {
    withAppBuildGradle,
    withProjectBuildGradle,
    withMainApplication,
    withPlugins,
} = require('@expo/config-plugins');


const withMultidexMainApplication = (config) => {
    return withMainApplication(config, (config) => {
        config.modResults.contents = addMultidexMainApplication(
            config.modResults.contents
        );
        return config;
    });
};

function addMultidexMainApplication(contents) {
    // before we replace anything, we check if we already replaced it
    if (contents.match('class MainApplication extends androidx.multidex.MultiDexApplication')) {
        console.log('\x1b[33m%s\x1b[0m', '✔  imgLy Expo Config Plugin: skipped addMultidexMainApplication. Already found patched MainApplication');
        return contents;
    }
    // the actucal check
    const pattern = 'class MainApplication extends Application';
    const replacement =
        'class MainApplication extends androidx.multidex.MultiDexApplication';
    if (contents.match(pattern)) {
        return contents.replace(pattern, replacement);
    }
    throw new Error(
        'Cannot setup VideoEditor: MainApplication does not extend Application'
    );
}

const withMultidexAppBuildGradle = (config) => {
    return withAppBuildGradle(config, (config) => {
        config.modResults.contents = addMultidexAppBuildGradle(
            config.modResults.contents
        );
        return config;
    });
};

function addMultidexAppBuildGradle(contents) {
    // before we replace anything, we check if we already replaced it
    if (contents.match('@generated begin imgLyMultidexAppBuild')) {
        console.log('\x1b[33m%s\x1b[0m', '✔  imgLy Expo Config Plugin: Skipped addMultidexAppBuildGradle. Already injected.');
        return contents;
    }
    // the actucal check

    const addBottom = `
// @generated begin imgLyMultidexAppBuild - expo prebuild - (DO NOT MODIFY)
android {
    defaultConfig {
        multiDexEnabled true
    }
}
dependencies {
    implementation 'androidx.multidex:multidex:2.0.1'
}
// @generated end imgLyMultidexAppBuild - expo prebuild 
  `;
    return contents.concat(addBottom);
}

const withImgLyProjectBuildGradle = (
    config, {
        version
    }
) => {
    return withProjectBuildGradle(config, (config) => {
        config.modResults.contents = addImgLy(config.modResults.contents, version);
        return config;
    });
};

function addImgLy(contents, version) {
    // before we replace anything, we check if we already replaced it
    if (contents.match('@generated begin addImgLy plugin')) {
        console.log('\x1b[33m%s\x1b[0m', '✔  imgLy Expo Config Plugin: Skipped addImgLy. Already found dependencies');
        return contents;
    }
    // the actucal check

    const addTop = `
// @generated begin addImgLy plugin - expo prebuild - (DO NOT MODIFY)
buildscript {
    repositories {
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://artifactory.img.ly/artifactory/imgly" }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10"
        classpath 'ly.img.android.sdk:plugin:${version}'
    }
}
// @generated end imgLyMultidexAppBuild - expo prebuild - (DO NOT MODIFY)

  `;
    return addTop.concat(contents);
}

const withVESDKConfig = (config) => {
    return withAppBuildGradle(config, (config) => {
        config.modResults.contents = addVideoEditorSDKConfig(
            config.modResults.contents
        );
        return config;
    });
};

function addVideoEditorSDKConfig(contents) {
    // before we replace anything, we check if we already replaced it
    if (contents.match('@generated begin addVideoEditorSDKConfig')) {
        console.log('\x1b[33m%s\x1b[0m', '✔  imgLy Expo Config Plugin: Skipped addVideoEditorSDKConfig. Already found imgly SDK Config');
        return contents;
    }
    // the actucal check
    const pattern = 'apply plugin: "com.android.application"';
    const addAfter = `
// @generated begin addVideoEditorSDKConfig - expo prebuild - (DO NOT MODIFY)
apply plugin: 'ly.img.android.sdk'
apply plugin: 'kotlin-android'

// Comment out the modules you don't need, to save size.
imglyConfig {
    modules {
        include 'ui:text'
        include 'ui:focus'
        include 'ui:frame'
        include 'ui:brush'
        include 'ui:filter'
        include 'ui:sticker'
        include 'ui:overlay'
        include 'ui:transform'
        include 'ui:adjustment'
        include 'ui:text-design'
        include 'ui:video-trim'
        include 'ui:video-library'
        include 'ui:video-composition'
        include 'ui:audio-composition'

        // This module is big, remove the serializer if you don't need that feature.
        include 'backend:serializer'

        // Remove the asset packs you don't need, these are also big in size.
        include 'assets:font-basic'
        include 'assets:frame-basic'
        include 'assets:filter-basic'
        include 'assets:overlay-basic'
        include 'assets:sticker-shapes'
        include 'assets:sticker-emoticons'
        include 'assets:sticker-animated'

        include 'backend:sticker-animated'
        include 'backend:sticker-smart'
    }
}
// @generated end addVideoEditorSDKConfig - expo prebuild - (DO NOT MODIFY)
  `;
    if (contents.match(pattern)) {
        return contents.replace(pattern, pattern + addAfter);
    }
    throw new Error(
        'Cannot setup VideoEditor: plugin "com.android.application" not found'
    );
}

const withReactNativeVideoEditorSDK = (
    config, {
        imgLyVersion = '9.1.1'
    } = {}
) => {
    return withPlugins(config, [
        withMultidexMainApplication,
        withMultidexAppBuildGradle,
        [withImgLyProjectBuildGradle, {
            version: imgLyVersion
        }],
        withVESDKConfig,
    ]);
};

module.exports = withReactNativeVideoEditorSDK;
```

I've updated the version to 9.1.1.
Waiting for a final statement if multidexMainApplication and multidex inserts are really necessary.

# Note
I've added some really unstable and ugly checks to prevent hundreds of re-insertions when calling `expo prebuild`. The current logic failed to built after the second prebuild command and duplicated all entries.

This plugin is likely to break apps for others and has to be adjusted to newer versions or your own project. For me, it is working perfectly fine now!

**Comment by leontobias** [comment]
@NoZiL @Hirbod Thank you for taking the time to build a solution. We are currently working on this internally and are in the testing phase for the config plugin.

This said, I hope that you understand that we can not merge this approach since we are working on a different one that adds support for both PhotoEditor SDK as well as VideoEditor SDK.

**Comment by hirbod** [comment]
@leonpesdk that was the answer I was hoping for :). Thanks a lot. The current approach is just a good workaround for now. Would be kinda nice to open up the issue tracker as well, for ideas, workarounds and maybe feature requests (I know you guys handle this through your ticketing)

**Comment by hirbod** [comment]
@leonpesdk while you guys are on it, please also think about localization. I haven't found any way for expo users to add languages. Ideally, the expo config plugin could create plist dictionary entries (based on a file) for iOS and copying over the strings.xml for android. We should ideally be able to define the files based on a language key. (de.json/de.xml etc)

Or please provide a way to translate everything inside the app (like loading a translation json or something)
And also copy over res/values/imgly_color.xml in order to be able to theme it with a theme.xml file.

**Comment by schiewe** [comment]
FYI: We just released our Expo config plugin support in version [2.12.0](https://github.com/imgly/vesdk-react-native/releases/tag/2.12.0) that's why I am closing this PR. Feel free to reach out to our [service desk](https://support.img.ly/) if you encounter any issues.

**Comment by hirbod** [comment]
@schiewe @leonpesdk thank you very much for finalizing the expo plugin. These are great news. I only have one addition to make:

https://github.com/imgly/imgly-react-native/blob/main/plugin/src/constants.ts#L137

The fixed kotlin-gradle-plugin:1.4.10 can break and should be configurable.
In my case, I had to set this value to 1.5.30.

With the new plugin, I am not able to and I have to build a new config plugin or patch against your patches.
When you have different libraries installed, which use 1.5.30 for example, you have to be able to change this.

Could you please make this also configurable with the new expo plugin as a param prop?

**Comment by schiewe** [comment]
@hirbod Sure, I'll add it to our next dev cycle discussions...

**Comment by leontobias** [comment]
@hirbod We just released version `2.13.0` of the plugins bringing support to configure the Kotlin Gradle plugin version.

**Pull request closed without merging**
